# Generated by Django 3.0.7 on 2022-11-30 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_doctor_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='verify',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='verify',
        ),
    ]
